// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: checksum_request.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Parse request body with optimized format {files: {path: checksum}}
type ChecksumRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of file paths to their checksums
	Files         map[string]uint64 `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksumRequest) Reset() {
	*x = ChecksumRequest{}
	mi := &file_checksum_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksumRequest) ProtoMessage() {}

func (x *ChecksumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checksum_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksumRequest.ProtoReflect.Descriptor instead.
func (*ChecksumRequest) Descriptor() ([]byte, []int) {
	return file_checksum_request_proto_rawDescGZIP(), []int{0}
}

func (x *ChecksumRequest) GetFiles() map[string]uint64 {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_checksum_request_proto protoreflect.FileDescriptor

const file_checksum_request_proto_rawDesc = "" +
	"\n" +
	"\x16checksum_request.proto\x12\x0fchrysalis.types\"\x8e\x01\n" +
	"\x0fChecksumRequest\x12A\n" +
	"\x05files\x18\x01 \x03(\v2+.chrysalis.types.ChecksumRequest.FilesEntryR\x05files\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B.Z,github.com/harness/ti-client/chrysalis/typesb\x06proto3"

var (
	file_checksum_request_proto_rawDescOnce sync.Once
	file_checksum_request_proto_rawDescData []byte
)

func file_checksum_request_proto_rawDescGZIP() []byte {
	file_checksum_request_proto_rawDescOnce.Do(func() {
		file_checksum_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checksum_request_proto_rawDesc), len(file_checksum_request_proto_rawDesc)))
	})
	return file_checksum_request_proto_rawDescData
}

var file_checksum_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checksum_request_proto_goTypes = []any{
	(*ChecksumRequest)(nil), // 0: chrysalis.types.ChecksumRequest
	nil,                     // 1: chrysalis.types.ChecksumRequest.FilesEntry
}
var file_checksum_request_proto_depIdxs = []int32{
	1, // 0: chrysalis.types.ChecksumRequest.files:type_name -> chrysalis.types.ChecksumRequest.FilesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_checksum_request_proto_init() }
func file_checksum_request_proto_init() {
	if File_checksum_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checksum_request_proto_rawDesc), len(file_checksum_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checksum_request_proto_goTypes,
		DependencyIndexes: file_checksum_request_proto_depIdxs,
		MessageInfos:      file_checksum_request_proto_msgTypes,
	}.Build()
	File_checksum_request_proto = out.File
	file_checksum_request_proto_goTypes = nil
	file_checksum_request_proto_depIdxs = nil
}
