// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: upload_cg_request.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadCgRequest represents a request to upload code graph data including tests and chains
type UploadCgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *Identifier            `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Tests         []*Test                `protobuf:"bytes,2,rep,name=tests,proto3" json:"tests,omitempty"`
	Chains        []*Chain               `protobuf:"bytes,3,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCgRequest) Reset() {
	*x = UploadCgRequest{}
	mi := &file_upload_cg_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCgRequest) ProtoMessage() {}

func (x *UploadCgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_cg_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCgRequest.ProtoReflect.Descriptor instead.
func (*UploadCgRequest) Descriptor() ([]byte, []int) {
	return file_upload_cg_request_proto_rawDescGZIP(), []int{0}
}

func (x *UploadCgRequest) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *UploadCgRequest) GetTests() []*Test {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *UploadCgRequest) GetChains() []*Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

var File_upload_cg_request_proto protoreflect.FileDescriptor

const file_upload_cg_request_proto_rawDesc = "" +
	"\n" +
	"\x17upload_cg_request.proto\x12\x0fchrysalis.types\x1a\x10identifier.proto\x1a\n" +
	"test.proto\x1a\vchain.proto\"\xab\x01\n" +
	"\x0fUploadCgRequest\x12;\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x1b.chrysalis.types.IdentifierR\n" +
	"identifier\x12+\n" +
	"\x05tests\x18\x02 \x03(\v2\x15.chrysalis.types.TestR\x05tests\x12.\n" +
	"\x06chains\x18\x03 \x03(\v2\x16.chrysalis.types.ChainR\x06chainsB.Z,github.com/harness/ti-client/chrysalis/typesb\x06proto3"

var (
	file_upload_cg_request_proto_rawDescOnce sync.Once
	file_upload_cg_request_proto_rawDescData []byte
)

func file_upload_cg_request_proto_rawDescGZIP() []byte {
	file_upload_cg_request_proto_rawDescOnce.Do(func() {
		file_upload_cg_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upload_cg_request_proto_rawDesc), len(file_upload_cg_request_proto_rawDesc)))
	})
	return file_upload_cg_request_proto_rawDescData
}

var file_upload_cg_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_upload_cg_request_proto_goTypes = []any{
	(*UploadCgRequest)(nil), // 0: chrysalis.types.UploadCgRequest
	(*Identifier)(nil),      // 1: chrysalis.types.Identifier
	(*Test)(nil),            // 2: chrysalis.types.Test
	(*Chain)(nil),           // 3: chrysalis.types.Chain
}
var file_upload_cg_request_proto_depIdxs = []int32{
	1, // 0: chrysalis.types.UploadCgRequest.identifier:type_name -> chrysalis.types.Identifier
	2, // 1: chrysalis.types.UploadCgRequest.tests:type_name -> chrysalis.types.Test
	3, // 2: chrysalis.types.UploadCgRequest.chains:type_name -> chrysalis.types.Chain
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_upload_cg_request_proto_init() }
func file_upload_cg_request_proto_init() {
	if File_upload_cg_request_proto != nil {
		return
	}
	file_identifier_proto_init()
	file_test_proto_init()
	file_chain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upload_cg_request_proto_rawDesc), len(file_upload_cg_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_upload_cg_request_proto_goTypes,
		DependencyIndexes: file_upload_cg_request_proto_depIdxs,
		MessageInfos:      file_upload_cg_request_proto_msgTypes,
	}.Build()
	File_upload_cg_request_proto = out.File
	file_upload_cg_request_proto_goTypes = nil
	file_upload_cg_request_proto_depIdxs = nil
}
